export const tableRows = [
  {
    id: 'WO-10482',
    asset: 'PMP-NPL-04B-HTX-PRIMARY-CIRCULATION-SKID-A12',
    site: 'North Plant',
    status: 'Ready',
    owner: 'J. Rivera',
    priority: 'High',
    price: 2847.5,
    updated: '2026-05-28',
    category: 'Mechanical',
  },
  {
    id: 'WO-10479',
    asset: 'CNV-DCK-07-OUTBOUND-SORTATION-LINE-BELT-DRIVE',
    site: null,
    status: 'In progress',
    owner: 'S. Chen',
    priority: 'Medium',
    price: 12990,
    updated: '2026-05-28',
    category: 'Electrical',
  },
  {
    id: 'WO-10471',
    asset: 'BLR-SYD-02-STEAM-GENERATION-HEADER-MANIFOLD',
    site: 'South Yard',
    status: 'Blocked',
    owner: 'M. Okonkwo',
    priority: 'Critical',
    price: null,
    updated: '2026-05-27',
    category: 'Safety',
  },
  {
    id: 'WO-10465',
    asset: 'CHL-NPL-C4-PROCESS-CHILLED-WATER-LOOP',
    site: 'North Plant',
    status: 'Ready',
    owner: null,
    priority: 'Low',
    price: 456.25,
    updated: '2026-05-27',
    category: 'HVAC',
  },
  {
    id: 'WO-10458',
    asset: 'FLT-WHB-09-ELECTRIC-COUNTERBALANCE-TRUCK',
    site: 'Warehouse B',
    status: 'Closed',
    owner: 'L. Kim',
    priority: 'Medium',
    price: null,
    updated: '2026-05-26',
    category: 'Fleet',
  },
  {
    id: 'WO-10452',
    asset: 'CMP-DCK-X1-HIGH-PRESSURE-AIR-COMPRESSOR-RACK',
    site: 'Dock 3',
    status: 'In progress',
    owner: 'J. Rivera',
    priority: 'High',
    price: 7823.99,
    updated: '2026-05-26',
    category: 'Mechanical',
  },
  {
    id: 'WO-10448',
    asset: 'GEN-NPL-03B-BACKUP-DIESEL-GENERATOR-SET',
    site: 'North Plant',
    status: 'Ready',
    owner: 'T. Nguyen',
    priority: 'High',
    price: 15420,
    updated: '2026-05-25',
    category: 'Electrical',
  },
  {
    id: 'WO-10445',
    asset: 'VLV-SYD-18-MAIN-STEAM-ISOLATION-VALVE-ACTUATOR',
    site: 'South Yard',
    status: 'In progress',
    owner: 'R. Brooks',
    priority: 'Medium',
    price: 1895.75,
    updated: '2026-05-25',
    category: 'Mechanical',
  },
  {
    id: 'WO-10441',
    asset: 'HX-WHB-12-PLATE-HEAT-EXCHANGER-SERVICE-MODULE',
    site: 'Warehouse B',
    status: 'Ready',
    owner: 'K. Walsh',
    priority: 'Low',
    price: 632.4,
    updated: '2026-05-25',
    category: null,
  },
  {
    id: 'WO-10438',
    asset: 'PLC-DCK-02-SORTATION-CONTROLLER-CPU-RACK',
    site: 'Dock 3',
    status: 'Blocked',
    owner: 'S. Chen',
    priority: 'Critical',
    price: null,
    updated: '2026-05-24',
    category: 'Controls',
  },
  {
    id: 'WO-10435',
    asset: 'TNK-NPL-08-CHEMICAL-DOSING-DAY-TANK-ASSEMBLY',
    site: null,
    status: 'In progress',
    owner: 'A. Patel',
    priority: 'Medium',
    price: 4210,
    updated: '2026-05-24',
    category: 'Plumbing',
  },
  {
    id: 'WO-10432',
    asset: 'FAN-SYD-05-ROOF-EXHAUST-VENTILATION-UNIT',
    site: 'South Yard',
    status: 'Closed',
    owner: 'L. Kim',
    priority: 'Low',
    price: 1180.5,
    updated: '2026-05-24',
    category: 'HVAC',
  },
  {
    id: 'WO-10429',
    asset: 'PMP-DCK-11-FIRE-SUPPRESSION-JOCKEY-PUMP-SKID',
    site: 'Dock 3',
    status: 'Ready',
    owner: 'J. Rivera',
    priority: 'High',
    price: 9675.25,
    updated: '2026-05-23',
    category: 'Safety',
  },
  {
    id: 'WO-10426',
    asset: 'CRN-WHB-03-OVERHEAD-BRIDGE-CRANE-HOIST-MOTOR',
    site: 'Warehouse B',
    status: 'In progress',
    owner: 'M. Okonkwo',
    priority: 'High',
    price: 22140,
    updated: '2026-05-23',
    category: 'Fleet',
  },
  {
    id: 'WO-10423',
    asset: 'SNS-NPL-22-TANK-LEVEL-TRANSMITTER-LOOP-PAIR',
    site: 'North Plant',
    status: 'Ready',
    owner: null,
    priority: 'Medium',
    price: 890,
    updated: '2026-05-23',
    category: 'Instrumentation',
  },
  {
    id: 'WO-10420',
    asset: 'MTR-SYD-14-CONVEYOR-DRIVE-VFD-PANEL-UNIT',
    site: 'South Yard',
    status: 'Blocked',
    owner: 'R. Brooks',
    priority: 'Critical',
    price: 5430.8,
    updated: '2026-05-22',
    category: 'Electrical',
  },
  {
    id: 'WO-10417',
    asset: 'FIL-WHB-06-AIR-HANDLING-UNIT-FILTER-BANK',
    site: 'Warehouse B',
    status: 'Ready',
    owner: 'K. Walsh',
    priority: 'Low',
    price: 312.99,
    updated: '2026-05-22',
    category: 'HVAC',
  },
  {
    id: 'WO-10414',
    asset: 'HTR-DCK-04-LOADING-DOCK-LEVELER-HYDRAULIC-PACK',
    site: 'Dock 3',
    status: 'In progress',
    owner: 'S. Chen',
    priority: 'Medium',
    price: 3675,
    updated: '2026-05-22',
    category: null,
  },
  {
    id: 'WO-10411',
    asset: 'TWR-NPL-01-COOLING-TOWER-FAN-GEARBOX-REBUILD',
    site: null,
    status: 'Closed',
    owner: null,
    priority: 'Medium',
    price: null,
    updated: '2026-05-21',
    category: 'Mechanical',
  },
  {
    id: 'WO-10408',
    asset: 'AGT-SYD-09-WASTEWATER-TREATMENT-BLOWER-SKID',
    site: 'South Yard',
    status: 'Ready',
    owner: 'J. Rivera',
    priority: 'High',
    price: 11250,
    updated: '2026-05-21',
    category: 'Plumbing',
  },
  {
    id: 'WO-10405',
    asset: 'LGT-WHB-15-WAREHOUSE-AISLE-EMERGENCY-LIGHTING',
    site: 'Warehouse B',
    status: 'In progress',
    owner: 'L. Kim',
    priority: 'Low',
    price: 745.6,
    updated: '2026-05-21',
    category: 'Electrical',
  },
  {
    id: 'WO-10402',
    asset: 'RFG-DCK-08-REFRIGERATED-CONTAINER-COMPRESSOR-UNIT',
    site: null,
    status: 'Ready',
    owner: 'T. Nguyen',
    priority: 'High',
    price: 18690,
    updated: '2026-05-20',
    category: null,
  },
  {
    id: 'WO-10399',
    asset: 'BRK-NPL-16-MAIN-ELECTRICAL-PANEL-BREAKER-FEED',
    site: 'North Plant',
    status: 'Blocked',
    owner: 'M. Okonkwo',
    priority: 'Critical',
    price: 2980.15,
    updated: '2026-05-20',
    category: 'Electrical',
  },
  {
    id: 'WO-10396',
    asset: 'SCL-SYD-03-PLATFORM-WEIGH-SCALE-LOAD-CELL-BANK',
    site: 'South Yard',
    status: 'In progress',
    owner: 'R. Brooks',
    priority: 'Medium',
    price: 4525,
    updated: '2026-05-20',
    category: 'Instrumentation',
  },
  {
    id: 'WO-10393',
    asset: 'DRY-WHB-02-INDUSTRIAL-LAUNDRY-TUMBLER-DRUM',
    site: 'Warehouse B',
    status: 'Ready',
    owner: null,
    priority: 'Low',
    price: 1675.3,
    updated: '2026-05-19',
    category: null,
  },
  {
    id: 'WO-10390',
    asset: 'UPS-DCK-05-SERVER-ROOM-BATTERY-BACKUP-CABINET',
    site: 'Dock 3',
    status: 'Closed',
    owner: 'S. Chen',
    priority: 'Medium',
    price: 8340,
    updated: '2026-05-19',
    category: 'Electrical',
  },
  {
    id: 'WO-10387',
    asset: 'LUB-NPL-07-CENTRAL-GREASE-DISTRIBUTION-MANIFOLD',
    site: 'North Plant',
    status: 'Ready',
    owner: 'A. Patel',
    priority: 'Low',
    price: 528.9,
    updated: '2026-05-19',
    category: 'Mechanical',
  },
  {
    id: 'WO-10384',
    asset: 'STR-SYD-11-STRUCTURAL-STEEL-COLUMN-ANCHOR-REPAIR',
    site: 'South Yard',
    status: 'In progress',
    owner: 'J. Rivera',
    priority: 'High',
    price: 6740,
    updated: '2026-05-18',
    category: 'Safety',
  },
]

const priceFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
})

export function formatPrice(price) {
  if (price == null) return null
  return priceFormatter.format(price)
}
